### ISSUE TITLE
Only raise UAC prompt if necessary

### ISSUE THREAD

**Issue by GitMensch** [gup4win/wingup#18]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/376 mentions the problem about updating user plugins.

Feature request:

* remove the elevation in the manifest https://github.com/gup4win/wingup/blob/master/src/gup.exe.manifest
* start update process by reading gup.xml and checking where to update the files, too
* [self-elevate gup from within the application][1] if files need to be updated that the user doesn't have write access for

[1]:https://support.microsoft.com/en-us/help/981778/how-to-self-elevate-an-application-to-a-high-privilege-level-under-uac

**Comment by yamlfd** [comment]
Is there a maintainer able to move this bug to a solution, please?

**Comment by donho** [comment]
@yamlfd  Normally it'll be much faster if you can suggest your solution (via PR).

**Comment by yamlfd** [comment]
The title says it already. 

Please keep in mind that it was correct in older notepad++ 6.x and is now broken for more than 1year. A normal user can install plugins to appdata and UAC causes serious malfunctions here as UAC cannot access the network drive. This need to be removed. Only if a user ha no permissions on c:\ the UAC i required. Additionally a UAC promt a normal user cannot answer as he has not enough permission and for god sake - he has not the administrator password.

**Comment by chcg** [comment]
@GitMensch @alexhass The correct place is https://github.com/bruderstein/nppPluginManager/issues/, maybe related to https://github.com/bruderstein/nppPluginManager/issues/35

Could you please create a new issue with some infos regarding the affected version N++ and PM.

@donho Could you please close this one.

**Comment by alexhass** [comment]
bruderstein is out of business as I know, see https://notepad-plus-plus.org/news/notepad-7.5-released.html. And the bug is here and not in the pulgin manager.

**Comment by chcg** [comment]
@alexhass The ticket description here is not quite clear. If it is affecting plugin updating the affected project is the pluginmanager which contains gpup.exe. This project here is gup.exe which takes care about updating notepad++ itself.

See https://htmlpreview.github.io/?https://github.com/bruderstein/nppPluginManager/blob/master/doc/index.html#install:

> To install the plugin manager, simply download (links below) the .zip, and place the PluginManager.dll file in the Notepad++ plugins directory, and the gpup.exe in the updater directory under your Notepad++ program directory. (e.g. "C:\Program Files\Notepad++\updater")
