### ISSUE TITLE
Curl 7.75.0 with CVE fixes available

### ISSUE THREAD

**Issue by chcg** [gup4win/wingup#20]
See https://curl.haxx.se/changes.html#7_57_0 with some CVEs, so the included version in wingup should be probably updated also.

**Comment by chcg** [comment]
@donho In the meantime https://curl.haxx.se/changes.html#7_60_0 is available with further CVE fixes also these onces are probably not relevant here.

**Comment by mere-human** [comment]
Adding a curl using git submodule could probably make its update easier.

**Comment by chcg** [comment]
Curl ist available at https://github.com/curl/curl

**Comment by donho** [comment]
@chcg 
Sorry for the late reply. (I've missed the notifications of GitHub since longtime ago. It's fixed, so feel free to tag me now).
I will update cURL to the recent version (7.75) - it means also the same update for [WinGup for Notepad++](https://github.com/notepad-plus-plus/wingup).
