### ISSUE TITLE
Absolutely no security?

### ISSUE THREAD

**Issue by Narvey** [gup4win/wingup#25]
I don't see any mention of checking file signatures upon downloading the update, or even hashes (which generally isn't sufficient, especially if SHA1 or *gasp* something even more broken). 

Maybe I'm just missing something, but it looks like this was thrown together with no regard to security.

**Comment by beppe9000** [comment]
A worm could easily search for and edit all gup xml files to spread itself or do privilege escalation if an app that uses gup is run as administrator and stored in app data for example.

**Comment by donho** [comment]
Checking SHA1 doesn't really makes sense, because it means you should know the SHA1 of binary of NEXT version.
OTOH, checking the signature of certificate is possible.
I'll see what I can do for it.

**Comment by donho** [comment]
Even for checking the signature of certificate there will be a problem:
For checking the signature we have to verify (at least) 1. signer display name 2. signer subject 3. signer key id
These 3 info can be put into `gup.xml` for comparing with the signature info of installer downloaded by GUp - GUp compares the info and launch the installer if the comparisons are OK. It will work until an installer signed by another (new) certificate. In the new certificate signer display name & signer subject might be the same, but signer key id will be changed.
So it's the same problem with checking SHA1 - we cannot know the key id (even the signer subject) of FUTURE certificate (the 3 info are deployed with the GUp), so the GUp will reject any new package signed by a new certificate.

If anyone has the solution, please comment here, I will reconsider this feature and reopen this issue.

**Comment by Narvey** [comment]
Generally how it is done is to sign the new cert with the old. This enables an absolute verification that they are the same person, unless the reason the cert was changed was because of private key leak (in which case it is game over anyway, so don't leak your private keys).
